#!/bin/sh

#
# Starts udhcpc in background mode
#

case "$1" in
  start)
	printf "Starting network: "
	/sbin/udhcpc -b
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	killall udhcpc
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

