#!/bin/sh

#
# Starts udhcpc in background mode
#

case "$1" in
  start)
	printf "Starting network: "
	start-stop-daemon -S -q -b -m -p /var/run/udhcpc.pid \
		--exec /sbin/udhcpc -- -f
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping network: "
	start-stop-daemon -K -q -p /var/run/udhcpc.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
